#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
# PS1='[\u@\h \W]\$ '

if [ -n "$CONTAINER_ID" ]; then
    PS1='\[\e[36m\][\u@'"$CONTAINER_ID"' \W]\$\[\e[0m\] '
else
    PS1="\[\e[1;36m\]┌───[\[\e[1;32m\]\u@\h\[\e[1;36m\]]──[\[\e[1;33m\]\w\[\e[1;36m\]]\[\e[1;35m\]\[\e[1;36m\]\n└───\[\e[1;32m\]❯ \[\e[0m\]"
fi

