#!/bin/sh

if ! command -v brightnessctl >/dev/null; then
    exit 0;
fi

DEFAULT_STEP=5

get_brightness() {
    max=$(brightnessctl max)
    cur=$(brightnessctl get)
    echo $(( (cur * 100 + max / 2) / max ))
}

CHANGE=0
BRIGHTNESS=-1

while true; do
    case $1 in
        -i|--increase)
            CHANGE=$((${2:-$DEFAULT_STEP}))
            shift;;
        -d|--decrease)
            CHANGE=$((-${2:-$DEFAULT_STEP}))
            shift;;
        --set)
            BRIGHTNESS=$(($2))
            shift;;
        *)
            break
            ;;
    esac
    shift
done

if [ "$CHANGE" -ne 0 ]; then
    if [ "$CHANGE" -gt 0 ]; then
        brightnessctl -q set "${CHANGE}%+"
    else
        ABS=${CHANGE#-}
        brightnessctl -q set "${ABS}%-"
    fi
elif [ "$BRIGHTNESS" -ge 0 ]; then
    brightnessctl -q set "${BRIGHTNESS}%"
fi

if ! command -v notify-send >/dev/null; then
    exit 0;
fi

BRIGHTNESS=$(get_brightness)
TEXT="Brightness : ${BRIGHTNESS}%"

notify-send \
    --app-name niri \
    --expire-time 1000 \
    --hint string:x-canonical-private-synchronous:brightness \
    --hint "int:value:$BRIGHTNESS" \
    --transient \
    "${TEXT}"